name: 'PR Dependency Check'
description: 'Verify PR dependencies are merged or closed'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: 'node16'
  main: 'index.js'
inputs:
  custom-domains:
    description: 'Define custom domains other than "github.com"'
    required: false
    default: []